server:
  port: 8888  # Config Server runs on port 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-username/the96farm-config-repo  # Replace with your actual GitHub repo
          clone-on-start: true
