server:
  port: 8085

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/the96farm-notifications
  mail:
    host: smtp.gmail.com
    port: 587
    username: shendepiyush049@gmail.com  # Replace with your email
    password: Piyushshende@049  # Replace with your password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    config:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
